@startuml
top to bottom direction
skinparam packageStyle rect

cloud "openshift-cluster" {
    
    rectangle openshift [
        <b>Openshift project</b>
        ====
        - Openshift images
        - Openshift templates
    ]
    rectangle my [
        <b>My Openshift project</b>
        ====
        - My images
    ]
    rectangle tiller [
        <b>Tiller project</b>
        ===
        - tiller server
        
    ]
    rectangle cicd [
        <b>CI/CD project</b>
        ====
        - Jenkins
        - Nexus
        - SonarQube
        - Charts museum
        - Monocular
    ]
    rectangle dev
    rectangle staging
    rectangle prod

    openshift <-- cicd : use
    my <-- cicd : use
    cicd --> dev : apply
    cicd --> staging : apply
    cicd --> prod : apply
    dev -right-> staging : tag
    staging -right-> prod : tag
}

@enduml