@startuml
top to bottom direction
skinparam packageStyle rect

cloud "openshift-cluster" {
    
    rectangle openshift [
        <b>Openshift project</b>
        ====
        - Openshift images
        - Openshift templates
    ]
    rectangle my [
        <b>My Openshift project</b>
        ====
        - My images
    ]
    rectangle tiller [
        <b>Tiller project</b>
        ===
        - tiller server
        - helm repository
        - monocular
    ]
    rectangle cicd [
        <b>CI/CD project</b>
        ====
        - Jenkins
        - Nexus
        - SonarQube
    ]
    rectangle dev
    rectangle staging
    rectangle prod

    openshift <-- cicd : use
    my <-- cicd : use
    cicd --> tiller : jenkins request
    tiller --> cicd : install
    tiller --> dev : apply
    tiller --> staging : apply
    tiller --> prod : apply
    dev -right-> staging : tag
    staging -right-> prod : tag
}

@enduml